spring.application.name=matricula-process

# -------------------------------------------------------
# MongoDB
# -------------------------------------------------------
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/matriculas}
spring.data.mongodb.database=${MONGODB_DATABASE:matriculas}

# -------------------------------------------------------
# Kafka ? Setup
# -------------------------------------------------------
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:matricula-process-group}
spring.kafka.consumer.auto-offset-reset=earliest

# -------------------------------------------------------
# Kafka ? Topics
# -------------------------------------------------------
kafka.topics.turma-atualizada=${KAFKA_TOPIC_TURMA_ATUALIZADA:turma-atualizada}
kafka.topics.matricula-atualizada=${KAFKA_TOPIC_MATRICULA_ATUALIZADA:matricula-atualizada}

# -------------------------------------------------------
# API Ciclos
# -------------------------------------------------------
ciclo.api.url=${CICLO_API_URL:http://localhost:8081}
